// Generated by CoffeeScript 1.6.3
(function() {
  var pipe, split, stdin, stdout, trans;

  split = require('split')();

  trans = require('stream').Transform({
    decodeStrings: false
  });

  stdin = process.stdin, stdout = process.stdout;

  process.stdout.on('error', process.exit);

  pipe = {};

  pipe.through = function(filter) {
    trans._transform = function(data, enc, done) {
      var result;
      if (data) {
        data = JSON.parse(data);
        result = filter(data);
        if (result) {
          this.push(JSON.stringify(result) + "\n");
        }
      }
      return done();
    };
    return stdin.pipe(split).pipe(trans).pipe(stdout);
  };

  module.exports = pipe;

}).call(this);
